### ISSUE TITLE
HAVT代码运行报错的询问

### ISSUE THREAD

**Issue by 895318** [OhJackHu/DAVT#2]
作者你好，感谢你的工作！我在用CUB数据集复现HAVT代码时遇到如下bug不知道如何解决，希望能得到你的回复：
Traceback (most recent call last):
  File "train.py", line 445, in <module>
    main()
  File "train.py", line 441, in main
    train(args, model)
  File "train.py", line 256, in train
    img_crop, img_drop = attention_crop_drop(attns, x)
  File "/root/autodl-tmp/HAVT-main/attentions.py", line 13, in attention_crop_drop
    batch_size, num_parts, height, width = attention_maps.shape
AttributeError: 'list' object has no attribute 'shape'

我通过查看语句loss1, logits, attns = model(x, y)返回的attns，发现attns是一个包含12个tensor的列表.....
attns具体应该长什么样子呢...如果就是12个tensor的列表的话，我将如何返回 batch_size, num_parts, height, width？

**Comment by RuiXing123** [comment]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/code/HAVT/train.py", line 442, in <module>
[rank0]:     main()
[rank0]:   File "/data/code/HAVT/train.py", line 438, in main
[rank0]:     train(args, model)
[rank0]:   File "/data/code/HAVT/train.py", line 252, in train
[rank0]:     img_crop, img_drop = attention_crop_drop(attns, x)
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/data/code/HAVT/attentions.py", line 14, in attention_crop_drop
[rank0]:     batch_size, num_parts, height, width = attention_maps.shape
[rank0]:                                            ^^^^^^^^^^^^^^^^^^^^
[rank0]: AttributeError: 'list' object has no attribute 'shape'

我遇到了同样的问题
